name: Code Review

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_KEY: pagopa_pagopa-api-config

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-review:
    name: Code Review Job
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      #
      - name: package install
        run:  npm install
      #
      - name: lint
        run:  npm run lint
      #
      - name: test
        run:  npm run test:coverage
      #
      - name: SonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=pagopa
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
      #
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
      #
      - name: Archive test results
        uses: actions/upload-artifact@v2
        working-directory: coverage
        with:
          name: test-report
          path: test-report.xml
      #
      - name: Archive lint results
        uses: actions/upload-artifact@v2
        working-directory: coverage
        with:
          name: lint-report
          path: lint-report.json